# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PreferenceUI.ui'
##
## Created by: Qt User Interface Compiler version 6.5.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QGridLayout,
    QGroupBox, QLabel, QScrollArea, QSizePolicy,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setWindowModality(Qt.ApplicationModal)
        Form.resize(1226, 1233)
        Form.setContextMenuPolicy(Qt.NoContextMenu)
        Form.setWindowTitle(u"Preferences")
        Form.setInputMethodHints(Qt.ImhNone)
        self.scrollArea = QScrollArea(Form)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 5, 476, 856))
        self.scrollArea.setFrameShape(QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 459, 856))
        self.tabWidget = QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 436, 841))
        self.tabWidget.setAutoFillBackground(False)
        self.TitleBlock = QWidget()
        self.TitleBlock.setObjectName(u"TitleBlock")
        self.groupBox_DrawingNumber = QGroupBox(self.TitleBlock)
        self.groupBox_DrawingNumber.setObjectName(u"groupBox_DrawingNumber")
        self.groupBox_DrawingNumber.setEnabled(True)
        self.groupBox_DrawingNumber.setGeometry(QRect(5, 10, 421, 101))
        self.groupBox_DrawingNumber.setMinimumSize(QSize(0, 101))
        font = QFont()
        font.setBold(True)
        self.groupBox_DrawingNumber.setFont(font)
        self.groupBox_DrawingNumber.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.groupBox_DrawingNumber.setFlat(False)
        self.UseFileName = Gui_PrefCheckBox(self.groupBox_DrawingNumber)
        self.UseFileName.setObjectName(u"UseFileName")
        self.UseFileName.setGeometry(QRect(10, 25, 241, 17))
        font1 = QFont()
        font1.setBold(False)
        self.UseFileName.setFont(font1)
        self.UseFileName.setProperty("prefEntry", u"UseFileName")
        self.UseFileName.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.DrawingNumber = Gui_PrefLineEdit(self.groupBox_DrawingNumber)
        self.DrawingNumber.setObjectName(u"DrawingNumber")
        self.DrawingNumber.setEnabled(False)
        self.DrawingNumber.setGeometry(QRect(10, 70, 241, 20))
        self.DrawingNumber.setFont(font1)
        self.DrawingNumber.setProperty("prefEntry", u"DrwNrFieldName")
        self.DrawingNumber.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.label_10 = QLabel(self.groupBox_DrawingNumber)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setEnabled(False)
        self.label_10.setGeometry(QRect(10, 50, 256, 16))
        self.label_10.setFont(font1)
        self.groupBox_Map_Items = QGroupBox(self.TitleBlock)
        self.groupBox_Map_Items.setObjectName(u"groupBox_Map_Items")
        self.groupBox_Map_Items.setGeometry(QRect(5, 120, 421, 176))
        self.groupBox_Map_Items.setMinimumSize(QSize(0, 176))
        self.groupBox_Map_Items.setFont(font)
        self.label_3 = QLabel(self.groupBox_Map_Items)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 20, 321, 36))
        self.label_3.setFont(font1)
        self.label_3.setTextFormat(Qt.AutoText)
        self.label_3.setWordWrap(True)
        self.layoutWidget = QWidget(self.groupBox_Map_Items)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 65, 281, 100))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.MapLength = Gui_PrefLineEdit(self.layoutWidget)
        self.MapLength.setObjectName(u"MapLength")
        self.MapLength.setFont(font1)
        self.MapLength.setProperty("prefEntry", u"MapLength")
        self.MapLength.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout.addWidget(self.MapLength, 0, 1, 1, 1)

        self.label_8 = QLabel(self.layoutWidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFont(font1)

        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)

        self.MapAngle = Gui_PrefLineEdit(self.layoutWidget)
        self.MapAngle.setObjectName(u"MapAngle")
        self.MapAngle.setFont(font1)
        self.MapAngle.setProperty("prefEntry", u"MapAngle")
        self.MapAngle.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout.addWidget(self.MapAngle, 1, 1, 1, 1)

        self.MapMass = Gui_PrefLineEdit(self.layoutWidget)
        self.MapMass.setObjectName(u"MapMass")
        self.MapMass.setFont(font1)
        self.MapMass.setProperty("prefEntry", u"MapMass")
        self.MapMass.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout.addWidget(self.MapMass, 2, 1, 1, 1)

        self.MapNoSheets = Gui_PrefLineEdit(self.layoutWidget)
        self.MapNoSheets.setObjectName(u"MapNoSheets")
        self.MapNoSheets.setFont(font1)
        self.MapNoSheets.setInputMethodHints(Qt.ImhNone)
        self.MapNoSheets.setProperty("prefEntry", u"MapNoSheets")
        self.MapNoSheets.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout.addWidget(self.MapNoSheets, 3, 1, 1, 1)

        self.label_7 = QLabel(self.layoutWidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font1)

        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)

        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFont(font1)

        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)

        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font1)

        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)

        self.groupBox_Included_Items = QGroupBox(self.TitleBlock)
        self.groupBox_Included_Items.setObjectName(u"groupBox_Included_Items")
        self.groupBox_Included_Items.setGeometry(QRect(5, 620, 421, 181))
        self.groupBox_Included_Items.setMinimumSize(QSize(0, 181))
        self.groupBox_Included_Items.setFont(font)
        self.label_4 = QLabel(self.groupBox_Included_Items)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 396, 61))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setFont(font1)
        self.label_4.setTextFormat(Qt.RichText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_4.setWordWrap(True)
        self.layoutWidget1 = QWidget(self.groupBox_Included_Items)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(10, 80, 144, 88))
        self.verticalLayout = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.IncludeLengthUnit = Gui_PrefCheckBox(self.layoutWidget1)
        self.IncludeLengthUnit.setObjectName(u"IncludeLengthUnit")
        self.IncludeLengthUnit.setFont(font1)
        self.IncludeLengthUnit.setProperty("prefEntry", u"IncludeLength")
        self.IncludeLengthUnit.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.verticalLayout.addWidget(self.IncludeLengthUnit)

        self.IncludeAngleUnit = Gui_PrefCheckBox(self.layoutWidget1)
        self.IncludeAngleUnit.setObjectName(u"IncludeAngleUnit")
        self.IncludeAngleUnit.setFont(font1)
        self.IncludeAngleUnit.setProperty("prefEntry", u"IncludeAngle")
        self.IncludeAngleUnit.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.verticalLayout.addWidget(self.IncludeAngleUnit)

        self.IncludeMassUnit = Gui_PrefCheckBox(self.layoutWidget1)
        self.IncludeMassUnit.setObjectName(u"IncludeMassUnit")
        self.IncludeMassUnit.setFont(font1)
        self.IncludeMassUnit.setProperty("prefEntry", u"IncludeMass")
        self.IncludeMassUnit.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.verticalLayout.addWidget(self.IncludeMassUnit)

        self.IncludeNoOfSheets = Gui_PrefCheckBox(self.layoutWidget1)
        self.IncludeNoOfSheets.setObjectName(u"IncludeNoOfSheets")
        self.IncludeNoOfSheets.setFont(font1)
        self.IncludeNoOfSheets.setProperty("prefEntry", u"IncludeNoOfSheets")
        self.IncludeNoOfSheets.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.verticalLayout.addWidget(self.IncludeNoOfSheets)

        self.groupBox_Map_DocInfo = QGroupBox(self.TitleBlock)
        self.groupBox_Map_DocInfo.setObjectName(u"groupBox_Map_DocInfo")
        self.groupBox_Map_DocInfo.setGeometry(QRect(5, 305, 421, 311))
        self.groupBox_Map_DocInfo.setMinimumSize(QSize(0, 176))
        self.groupBox_Map_DocInfo.setFont(font)
        self.label_17 = QLabel(self.groupBox_Map_DocInfo)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 20, 321, 36))
        self.label_17.setFont(font1)
        self.label_17.setTextFormat(Qt.AutoText)
        self.label_17.setWordWrap(True)
        self.layoutWidget2 = QWidget(self.groupBox_Map_DocInfo)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(11, 66, 246, 230))
        self.gridLayout_2 = QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_20 = QLabel(self.layoutWidget2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setFont(font1)

        self.gridLayout_2.addWidget(self.label_20, 0, 0, 1, 1)

        self.DocInfo_Name = Gui_PrefLineEdit(self.layoutWidget2)
        self.DocInfo_Name.setObjectName(u"DocInfo_Name")
        self.DocInfo_Name.setFont(font1)
        self.DocInfo_Name.setProperty("prefEntry", u"DocInfo_Name")
        self.DocInfo_Name.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout_2.addWidget(self.DocInfo_Name, 0, 1, 1, 2)

        self.label_21 = QLabel(self.layoutWidget2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setFont(font1)

        self.gridLayout_2.addWidget(self.label_21, 1, 0, 1, 1)

        self.DocInfo_CreatedBy = Gui_PrefLineEdit(self.layoutWidget2)
        self.DocInfo_CreatedBy.setObjectName(u"DocInfo_CreatedBy")
        self.DocInfo_CreatedBy.setFont(font1)
        self.DocInfo_CreatedBy.setProperty("prefEntry", u"DocInfo_CreatedBy")
        self.DocInfo_CreatedBy.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout_2.addWidget(self.DocInfo_CreatedBy, 1, 1, 1, 2)

        self.label_19 = QLabel(self.layoutWidget2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setFont(font1)

        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)

        self.DocInfo_CreatedDate = Gui_PrefLineEdit(self.layoutWidget2)
        self.DocInfo_CreatedDate.setObjectName(u"DocInfo_CreatedDate")
        self.DocInfo_CreatedDate.setFont(font1)
        self.DocInfo_CreatedDate.setProperty("prefEntry", u"DocInfo_CreatedDate")
        self.DocInfo_CreatedDate.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout_2.addWidget(self.DocInfo_CreatedDate, 2, 1, 1, 2)

        self.label_18 = QLabel(self.layoutWidget2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setFont(font1)

        self.gridLayout_2.addWidget(self.label_18, 3, 0, 1, 1)

        self.DocInfo_LastModifiedBy = Gui_PrefLineEdit(self.layoutWidget2)
        self.DocInfo_LastModifiedBy.setObjectName(u"DocInfo_LastModifiedBy")
        self.DocInfo_LastModifiedBy.setFont(font1)
        self.DocInfo_LastModifiedBy.setInputMethodHints(Qt.ImhNone)
        self.DocInfo_LastModifiedBy.setProperty("prefEntry", u"DocInfo_LastModifiedBy")
        self.DocInfo_LastModifiedBy.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout_2.addWidget(self.DocInfo_LastModifiedBy, 3, 1, 1, 2)

        self.label_22 = QLabel(self.layoutWidget2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setFont(font1)

        self.gridLayout_2.addWidget(self.label_22, 4, 0, 1, 1)

        self.DocInfo_LastModifiedDate = Gui_PrefLineEdit(self.layoutWidget2)
        self.DocInfo_LastModifiedDate.setObjectName(u"DocInfo_LastModifiedDate")
        self.DocInfo_LastModifiedDate.setFont(font1)
        self.DocInfo_LastModifiedDate.setInputMethodHints(Qt.ImhNone)
        self.DocInfo_LastModifiedDate.setProperty("prefEntry", u"DocInfo_LastModifiedDate")
        self.DocInfo_LastModifiedDate.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout_2.addWidget(self.DocInfo_LastModifiedDate, 4, 1, 1, 2)

        self.label_23 = QLabel(self.layoutWidget2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setFont(font1)

        self.gridLayout_2.addWidget(self.label_23, 5, 0, 1, 1)

        self.DocInfo_Company = Gui_PrefLineEdit(self.layoutWidget2)
        self.DocInfo_Company.setObjectName(u"DocInfo_Company")
        self.DocInfo_Company.setFont(font1)
        self.DocInfo_Company.setInputMethodHints(Qt.ImhNone)
        self.DocInfo_Company.setProperty("prefEntry", u"DocInfo_Company")
        self.DocInfo_Company.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout_2.addWidget(self.DocInfo_Company, 5, 1, 1, 2)

        self.label_24 = QLabel(self.layoutWidget2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setFont(font1)

        self.gridLayout_2.addWidget(self.label_24, 6, 0, 1, 1)

        self.DocInfo_License = Gui_PrefLineEdit(self.layoutWidget2)
        self.DocInfo_License.setObjectName(u"DocInfo_License")
        self.DocInfo_License.setFont(font1)
        self.DocInfo_License.setInputMethodHints(Qt.ImhNone)
        self.DocInfo_License.setProperty("prefEntry", u"DocInfo_License")
        self.DocInfo_License.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout_2.addWidget(self.DocInfo_License, 6, 1, 1, 2)

        self.label_25 = QLabel(self.layoutWidget2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setFont(font1)

        self.gridLayout_2.addWidget(self.label_25, 7, 0, 1, 1)

        self.DocInfo_LicenseURL = Gui_PrefLineEdit(self.layoutWidget2)
        self.DocInfo_LicenseURL.setObjectName(u"DocInfo_LicenseURL")
        self.DocInfo_LicenseURL.setFont(font1)
        self.DocInfo_LicenseURL.setInputMethodHints(Qt.ImhNone)
        self.DocInfo_LicenseURL.setProperty("prefEntry", u"DocInfo_LicenseURL")
        self.DocInfo_LicenseURL.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout_2.addWidget(self.DocInfo_LicenseURL, 7, 1, 1, 2)

        self.label_26 = QLabel(self.layoutWidget2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setFont(font1)

        self.gridLayout_2.addWidget(self.label_26, 8, 0, 1, 1)

        self.DocInfo_Comment = Gui_PrefLineEdit(self.layoutWidget2)
        self.DocInfo_Comment.setObjectName(u"DocInfo_Comment")
        self.DocInfo_Comment.setFont(font1)
        self.DocInfo_Comment.setInputMethodHints(Qt.ImhNone)
        self.DocInfo_Comment.setProperty("prefEntry", u"DocInfo_Comment")
        self.DocInfo_Comment.setProperty("prefPath", u"Mod/TitleBlock Workbench")

        self.gridLayout_2.addWidget(self.DocInfo_Comment, 8, 1, 1, 2)

        self.tabWidget.addTab(self.TitleBlock, "")
        self.External_Source = QWidget()
        self.External_Source.setObjectName(u"External_Source")
        self.groupBox_2 = QGroupBox(self.External_Source)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(5, 10, 421, 246))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy1)
        self.UseExternalSource = Gui_PrefCheckBox(self.groupBox_2)
        self.UseExternalSource.setObjectName(u"UseExternalSource")
        self.UseExternalSource.setGeometry(QRect(10, 25, 231, 17))
        self.UseExternalSource.setFont(font1)
        self.UseExternalSource.setProperty("prefEntry", u"UseExternalSource")
        self.UseExternalSource.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setEnabled(False)
        self.label_16.setGeometry(QRect(10, 85, 371, 16))
        self.label_16.setFont(font1)
        self.label_16.setFrameShadow(QFrame.Plain)
        self.label_16.setWordWrap(True)
        self.SheetName = Gui_PrefLineEdit(self.groupBox_2)
        self.SheetName.setObjectName(u"SheetName")
        self.SheetName.setEnabled(False)
        self.SheetName.setGeometry(QRect(10, 105, 361, 25))
        self.SheetName.setFont(font1)
        self.SheetName.setProperty("prefEntry", u"SheetName")
        self.SheetName.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.ExternalFileChooser = Gui_PrefFileChooser(self.groupBox_2)
        self.ExternalFileChooser.setObjectName(u"ExternalFileChooser")
        self.ExternalFileChooser.setEnabled(False)
        self.ExternalFileChooser.setGeometry(QRect(10, 45, 401, 25))
        self.ExternalFileChooser.setFont(font1)
        self.ExternalFileChooser.setProperty("prefEntry", u"ExternalFile")
        self.ExternalFileChooser.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setEnabled(False)
        self.label_15.setGeometry(QRect(10, 135, 341, 51))
        self.label_15.setFont(font1)
        self.label_15.setFrameShadow(QFrame.Plain)
        self.label_15.setWordWrap(True)
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QRect(170, 175, 216, 31))
        font2 = QFont()
        font2.setBold(False)
        font2.setItalic(True)
        self.label_2.setFont(font2)
        self.label_2.setWordWrap(True)
        self.StartCell = Gui_PrefLineEdit(self.groupBox_2)
        self.StartCell.setObjectName(u"StartCell")
        self.StartCell.setEnabled(False)
        self.StartCell.setGeometry(QRect(10, 180, 153, 25))
        self.StartCell.setFont(font1)
        self.StartCell.setProperty("prefEntry", u"StartCell")
        self.StartCell.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.AutoFillTitleBlock = Gui_PrefCheckBox(self.groupBox_2)
        self.AutoFillTitleBlock.setObjectName(u"AutoFillTitleBlock")
        self.AutoFillTitleBlock.setEnabled(False)
        self.AutoFillTitleBlock.setGeometry(QRect(10, 215, 158, 17))
        self.AutoFillTitleBlock.setFont(font1)
        self.AutoFillTitleBlock.setChecked(True)
        self.AutoFillTitleBlock.setProperty("prefEntry", u"AutoFillTitleBlock")
        self.AutoFillTitleBlock.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.groupBox_3 = QGroupBox(self.External_Source)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(5, 275, 421, 186))
        self.widget_ImportSettings = QWidget(self.groupBox_3)
        self.widget_ImportSettings.setObjectName(u"widget_ImportSettings")
        self.widget_ImportSettings.setEnabled(False)
        self.widget_ImportSettings.setGeometry(QRect(5, 20, 406, 156))
        self.ImportSettingsXL = Gui_PrefCheckBox(self.widget_ImportSettings)
        self.ImportSettingsXL.setObjectName(u"ImportSettingsXL")
        self.ImportSettingsXL.setEnabled(False)
        self.ImportSettingsXL.setGeometry(QRect(5, 10, 381, 17))
        self.ImportSettingsXL.setFont(font1)
        self.ImportSettingsXL.setProperty("prefEntry", u"ImportSettingsXL")
        self.ImportSettingsXL.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.SheetName_Settings = Gui_PrefLineEdit(self.widget_ImportSettings)
        self.SheetName_Settings.setObjectName(u"SheetName_Settings")
        self.SheetName_Settings.setEnabled(False)
        self.SheetName_Settings.setGeometry(QRect(5, 55, 133, 25))
        self.SheetName_Settings.setFont(font1)
        self.SheetName_Settings.setProperty("prefEntry", u"SheetName_Settings")
        self.SheetName_Settings.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.StartCell_Settings = Gui_PrefLineEdit(self.widget_ImportSettings)
        self.StartCell_Settings.setObjectName(u"StartCell_Settings")
        self.StartCell_Settings.setEnabled(False)
        self.StartCell_Settings.setGeometry(QRect(5, 125, 153, 25))
        self.StartCell_Settings.setFont(font1)
        self.StartCell_Settings.setProperty("prefEntry", u"StartCell_Settings")
        self.StartCell_Settings.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.label_9 = QLabel(self.widget_ImportSettings)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QRect(165, 120, 216, 31))
        self.label_9.setFont(font2)
        self.label_9.setWordWrap(True)
        self.label_13 = QLabel(self.widget_ImportSettings)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setEnabled(False)
        self.label_13.setGeometry(QRect(5, 85, 206, 36))
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy2)
        self.label_13.setFont(font1)
        self.label_13.setFrameShadow(QFrame.Plain)
        self.label_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_13.setWordWrap(True)
        self.label_14 = QLabel(self.widget_ImportSettings)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setEnabled(False)
        self.label_14.setGeometry(QRect(5, 35, 371, 16))
        self.label_14.setFont(font1)
        self.label_14.setFrameShadow(QFrame.Plain)
        self.label_14.setWordWrap(True)
        self.tabWidget.addTab(self.External_Source, "")
        self.TechDraw_Workbench = QWidget()
        self.TechDraw_Workbench.setObjectName(u"TechDraw_Workbench")
        self.groupBox = QGroupBox(self.TechDraw_Workbench)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(5, 10, 421, 476))
        sizePolicy1.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy1)
        self.AddToolBarTechDraw = Gui_PrefCheckBox(self.groupBox)
        self.AddToolBarTechDraw.setObjectName(u"AddToolBarTechDraw")
        self.AddToolBarTechDraw.setEnabled(True)
        self.AddToolBarTechDraw.setGeometry(QRect(11, 26, 219, 17))
        self.AddToolBarTechDraw.setFont(font1)
        self.AddToolBarTechDraw.setChecked(True)
        self.AddToolBarTechDraw.setProperty("prefEntry", u"AddToolBarTechDraw")
        self.AddToolBarTechDraw.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setEnabled(False)
        self.label_12.setGeometry(QRect(11, 72, 98, 16))
        self.Import_templates = Gui_PrefCheckBox(self.groupBox)
        self.Import_templates.setObjectName(u"Import_templates")
        self.Import_templates.setGeometry(QRect(11, 49, 148, 17))
        self.Import_templates.setProperty("prefEntry", u"Import_templates")
        self.Import_templates.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.Default_Template = Gui_PrefComboBox(self.groupBox)
        self.Default_Template.addItem("")
        self.Default_Template.addItem("")
        self.Default_Template.addItem("")
        self.Default_Template.addItem("")
        self.Default_Template.addItem("")
        self.Default_Template.addItem("")
        self.Default_Template.setObjectName(u"Default_Template")
        self.Default_Template.setEnabled(False)
        self.Default_Template.setGeometry(QRect(11, 91, 96, 20))
        self.Default_Template.setProperty("prefEntry", u"Default_Template")
        self.Default_Template.setProperty("prefPath", u"Mod/TitleBlock Workbench")
        self.tabWidget.addTab(self.TechDraw_Workbench, "")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        QWidget.setTabOrder(self.tabWidget, self.UseFileName)
        QWidget.setTabOrder(self.UseFileName, self.DrawingNumber)
        QWidget.setTabOrder(self.DrawingNumber, self.MapLength)
        QWidget.setTabOrder(self.MapLength, self.MapAngle)
        QWidget.setTabOrder(self.MapAngle, self.MapMass)
        QWidget.setTabOrder(self.MapMass, self.MapNoSheets)
        QWidget.setTabOrder(self.MapNoSheets, self.DocInfo_Name)
        QWidget.setTabOrder(self.DocInfo_Name, self.DocInfo_CreatedBy)
        QWidget.setTabOrder(self.DocInfo_CreatedBy, self.DocInfo_CreatedDate)
        QWidget.setTabOrder(self.DocInfo_CreatedDate, self.DocInfo_LastModifiedBy)
        QWidget.setTabOrder(self.DocInfo_LastModifiedBy, self.DocInfo_LastModifiedDate)
        QWidget.setTabOrder(self.DocInfo_LastModifiedDate, self.DocInfo_Company)
        QWidget.setTabOrder(self.DocInfo_Company, self.DocInfo_License)
        QWidget.setTabOrder(self.DocInfo_License, self.DocInfo_LicenseURL)
        QWidget.setTabOrder(self.DocInfo_LicenseURL, self.DocInfo_Comment)
        QWidget.setTabOrder(self.DocInfo_Comment, self.IncludeLengthUnit)
        QWidget.setTabOrder(self.IncludeLengthUnit, self.IncludeAngleUnit)
        QWidget.setTabOrder(self.IncludeAngleUnit, self.IncludeMassUnit)
        QWidget.setTabOrder(self.IncludeMassUnit, self.IncludeNoOfSheets)
        QWidget.setTabOrder(self.IncludeNoOfSheets, self.UseExternalSource)
        QWidget.setTabOrder(self.UseExternalSource, self.SheetName)
        QWidget.setTabOrder(self.SheetName, self.StartCell)
        QWidget.setTabOrder(self.StartCell, self.AutoFillTitleBlock)
        QWidget.setTabOrder(self.AutoFillTitleBlock, self.ImportSettingsXL)
        QWidget.setTabOrder(self.ImportSettingsXL, self.SheetName_Settings)
        QWidget.setTabOrder(self.SheetName_Settings, self.StartCell_Settings)
        QWidget.setTabOrder(self.StartCell_Settings, self.AddToolBarTechDraw)
        QWidget.setTabOrder(self.AddToolBarTechDraw, self.Import_templates)
        QWidget.setTabOrder(self.Import_templates, self.Default_Template)

        self.retranslateUi(Form)
        self.UseFileName.toggled.connect(self.DrawingNumber.setEnabled)
        self.Import_templates.toggled.connect(self.Default_Template.setEnabled)
        self.UseExternalSource.toggled.connect(self.label_2.setEnabled)
        self.ImportSettingsXL.toggled.connect(self.label_13.setEnabled)
        self.UseExternalSource.toggled.connect(self.widget_ImportSettings.setEnabled)
        self.UseExternalSource.toggled.connect(self.StartCell.setEnabled)
        self.ImportSettingsXL.toggled.connect(self.groupBox_Included_Items.setDisabled)
        self.ImportSettingsXL.toggled.connect(self.label_9.setEnabled)
        self.UseExternalSource.toggled.connect(self.ExternalFileChooser.setEnabled)
        self.ImportSettingsXL.toggled.connect(self.label_14.setEnabled)
        self.UseExternalSource.toggled.connect(self.label_15.setEnabled)
        self.UseExternalSource.toggled.connect(self.ImportSettingsXL.setEnabled)
        self.UseExternalSource.toggled.connect(self.SheetName.setEnabled)
        self.ImportSettingsXL.toggled.connect(self.StartCell_Settings.setEnabled)
        self.UseExternalSource.toggled.connect(self.ImportSettingsXL.setChecked)
        self.UseExternalSource.toggled.connect(self.label_16.setEnabled)
        self.Import_templates.toggled.connect(self.label_12.setEnabled)
        self.UseExternalSource.toggled.connect(self.AutoFillTitleBlock.setEnabled)
        self.UseFileName.toggled.connect(self.label_10.setEnabled)
        self.ImportSettingsXL.toggled.connect(self.groupBox_DrawingNumber.setDisabled)
        self.ImportSettingsXL.toggled.connect(self.SheetName_Settings.setEnabled)
        self.ImportSettingsXL.toggled.connect(self.groupBox_Map_Items.setDisabled)
        self.UseExternalSource.toggled.connect(self.groupBox_Map_DocInfo.setDisabled)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        self.groupBox_DrawingNumber.setTitle("")
        self.UseFileName.setText(QCoreApplication.translate("Form", u"Use filename as drawing number", None))
        self.DrawingNumber.setInputMask("")
        self.DrawingNumber.setText("")
        self.DrawingNumber.setPlaceholderText(QCoreApplication.translate("Form", u"Enter the property name...", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"The property name for drawing number:", None))
        self.groupBox_Map_Items.setTitle("")
        self.label_3.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>The following system properties can be mapped to the titleblock: <span style=\" font-style:italic;\">(If not applicalbe, leave empty.)</span></p></body></html>", None))
        self.MapLength.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Number of pages:", None))
        self.MapAngle.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.MapMass.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.MapNoSheets.setText("")
        self.MapNoSheets.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Mass unit:", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"Length unit:", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Angle unit:", None))
        self.groupBox_Included_Items.setTitle("")
        self.label_4.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>The following properties can be included from the system:</p><p><span style=\" font-style:italic;\">(When the titleblock does have one or more properties already, you will end up with duplicates! It is advised to map the properties instead)</span></p></body></html>", None))
        self.IncludeLengthUnit.setText(QCoreApplication.translate("Form", u"Include lengths", None))
        self.IncludeAngleUnit.setText(QCoreApplication.translate("Form", u"Include angles", None))
        self.IncludeMassUnit.setText(QCoreApplication.translate("Form", u"Include mass", None))
        self.IncludeNoOfSheets.setText(QCoreApplication.translate("Form", u"Include number of pages", None))
        self.groupBox_Map_DocInfo.setTitle("")
        self.label_17.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>The following document information values can be mapped to the titleblock: <span style=\" font-style:italic;\">(If not applicalbe, leave empty.)</span></p></body></html>", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"Name:", None))
        self.DocInfo_Name.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"Created by:", None))
        self.DocInfo_CreatedBy.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"Creation date:", None))
        self.DocInfo_CreatedDate.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"Last modified by:", None))
        self.DocInfo_LastModifiedBy.setText("")
        self.DocInfo_LastModifiedBy.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"Last modification by:", None))
        self.DocInfo_LastModifiedDate.setText("")
        self.DocInfo_LastModifiedDate.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"Company:", None))
        self.DocInfo_Company.setText("")
        self.DocInfo_Company.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"License information:", None))
        self.DocInfo_License.setText("")
        self.DocInfo_License.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"License URL:", None))
        self.DocInfo_LicenseURL.setText("")
        self.DocInfo_LicenseURL.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"Comment:", None))
        self.DocInfo_Comment.setText("")
        self.DocInfo_Comment.setPlaceholderText(QCoreApplication.translate("Form", u"Enter property name here...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TitleBlock), QCoreApplication.translate("Form", u"TitleBlock", None))
        self.groupBox_2.setTitle("")
        self.UseExternalSource.setText(QCoreApplication.translate("Form", u"Use external source", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>The name of the worksheet that contains the date for the titleblock:</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.SheetName.setToolTip(QCoreApplication.translate("Form", u"Enter the name of the sheet for the titleblock data", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.SheetName.setWhatsThis(QCoreApplication.translate("Form", u"Enter the name of the sheet for the titleblock data", None))
#endif // QT_CONFIG(whatsthis)
        self.SheetName.setInputMask("")
        self.SheetName.setText("")
        self.SheetName.setPlaceholderText(QCoreApplication.translate("Form", u"Enter the name of sheet...", None))
        self.ExternalFileChooser.setFileName("")
        self.ExternalFileChooser.setFilter(QCoreApplication.translate("Form", u"*.xlsx", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>The startcell of the table which contains to the data for the titleblock: <span style=\" font-style:italic;\">(This must be the top left cell.)</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>Cell adress must be like &quot;B1&quot; or like &quot;R1C1&quot;. If empty, A1 will be used.</p></body></html>", None))
        self.StartCell.setInputMask("")
        self.StartCell.setText("")
        self.StartCell.setPlaceholderText(QCoreApplication.translate("Form", u"Enter the start cell...", None))
        self.AutoFillTitleBlock.setText(QCoreApplication.translate("Form", u"Populate titleblock on import", None))
        self.groupBox_3.setTitle("")
        self.ImportSettingsXL.setText(QCoreApplication.translate("Form", u"Import workbench settings from external source", None))
#if QT_CONFIG(tooltip)
        self.SheetName_Settings.setToolTip(QCoreApplication.translate("Form", u"Enter the name of sheet to import the settings from.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.SheetName_Settings.setStatusTip(QCoreApplication.translate("Form", u"Enter the name of sheet to import the settings from.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.SheetName_Settings.setWhatsThis(QCoreApplication.translate("Form", u"Enter the name of sheet...", None))
#endif // QT_CONFIG(whatsthis)
        self.SheetName_Settings.setInputMask("")
        self.SheetName_Settings.setText("")
        self.SheetName_Settings.setPlaceholderText(QCoreApplication.translate("Form", u"Enter the name of sheet...", None))
#if QT_CONFIG(tooltip)
        self.StartCell_Settings.setToolTip(QCoreApplication.translate("Form", u"Enter the cell to import the settings from.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.StartCell_Settings.setWhatsThis(QCoreApplication.translate("Form", u"Enter the cell to import the settings from.", None))
#endif // QT_CONFIG(whatsthis)
        self.StartCell_Settings.setInputMask("")
        self.StartCell_Settings.setText("")
        self.StartCell_Settings.setPlaceholderText(QCoreApplication.translate("Form", u"Enter the start cell...", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>Cell adress must be like &quot;B1&quot; or like &quot;R1C1&quot;. If empty, A1 will be used.</p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>The startcell of the table with settings: <span style=\" font-style:italic;\">(This must be the top left cell.)</span></p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>The name of the worksheet that containts the table with settings:</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.External_Source), QCoreApplication.translate("Form", u"External Source", None))
        self.groupBox.setTitle("")
        self.AddToolBarTechDraw.setText(QCoreApplication.translate("Form", u"Add toolbar to the TechDraw Workbench", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Set default template", None))
        self.Import_templates.setText(QCoreApplication.translate("Form", u"Import example templates", None))
        self.Default_Template.setItemText(0, QCoreApplication.translate("Form", u"A0_Landscape", None))
        self.Default_Template.setItemText(1, QCoreApplication.translate("Form", u"A1_Landscape", None))
        self.Default_Template.setItemText(2, QCoreApplication.translate("Form", u"A2_Landscape", None))
        self.Default_Template.setItemText(3, QCoreApplication.translate("Form", u"A3_Landscape", None))
        self.Default_Template.setItemText(4, QCoreApplication.translate("Form", u"A4_Landscape", None))
        self.Default_Template.setItemText(5, QCoreApplication.translate("Form", u"A4_Portrait", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TechDraw_Workbench), QCoreApplication.translate("Form", u"TechDraw Workbench", None))
        pass
    # retranslateUi

