# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PreferenceUI.ui'
##
## Created by: Qt User Interface Compiler version 6.5.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QSizePolicy,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setWindowModality(Qt.ApplicationModal)
        Form.resize(980, 513)
        Form.setContextMenuPolicy(Qt.NoContextMenu)
        Form.setWindowTitle(u"Settings")
        Form.setInputMethodHints(Qt.ImhNone)
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(5, 290, 421, 101))
        font = QFont()
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.UseFileName = Gui_PrefCheckBox(self.groupBox)
        self.UseFileName.setObjectName(u"UseFileName")
        self.UseFileName.setGeometry(QRect(10, 20, 241, 17))
        font1 = QFont()
        font1.setBold(False)
        self.UseFileName.setFont(font1)
        self.UseFileName.setProperty("prefEntry", u"UseFileName")
        self.UseFileName.setProperty("prefPath", u"TechDrawTitleBlockUtility")
        self.urlLabel_2 = Gui_UrlLabel(self.groupBox)
        self.urlLabel_2.setObjectName(u"urlLabel_2")
        self.urlLabel_2.setEnabled(False)
        self.urlLabel_2.setGeometry(QRect(10, 50, 131, 16))
        self.urlLabel_2.setFont(font1)
        self.DrawingNumber = Gui_PrefLineEdit(self.groupBox)
        self.DrawingNumber.setObjectName(u"DrawingNumber")
        self.DrawingNumber.setEnabled(False)
        self.DrawingNumber.setGeometry(QRect(10, 70, 241, 20))
        self.DrawingNumber.setFont(font1)
        self.DrawingNumber.setProperty("prefEntry", u"DrwNrFieldName")
        self.DrawingNumber.setProperty("prefPath", u"TechDrawTitleBlockUtility")
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(5, 140, 421, 146))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.ExternalFileChooser = Gui_PrefFileChooser(self.groupBox_2)
        self.ExternalFileChooser.setObjectName(u"ExternalFileChooser")
        self.ExternalFileChooser.setEnabled(False)
        self.ExternalFileChooser.setGeometry(QRect(10, 40, 401, 23))
        self.ExternalFileChooser.setFont(font1)
        self.ExternalFileChooser.setProperty("prefEntry", u"ExternalFile")
        self.ExternalFileChooser.setProperty("prefPath", u"TechDrawTitleBlockUtility")
        self.UseExternalSource = Gui_PrefCheckBox(self.groupBox_2)
        self.UseExternalSource.setObjectName(u"UseExternalSource")
        self.UseExternalSource.setGeometry(QRect(10, 20, 231, 17))
        self.UseExternalSource.setFont(font1)
        self.UseExternalSource.setProperty("prefEntry", u"UseExternalSource")
        self.UseExternalSource.setProperty("prefPath", u"TechDrawTitleBlockUtility")
        self.SheetName = Gui_PrefLineEdit(self.groupBox_2)
        self.SheetName.setObjectName(u"SheetName")
        self.SheetName.setEnabled(False)
        self.SheetName.setGeometry(QRect(10, 70, 241, 20))
        self.SheetName.setFont(font1)
        self.SheetName.setProperty("prefEntry", u"SheetName")
        self.SheetName.setProperty("prefPath", u"TechDrawTitleBlockUtility")
        self.StartCell = Gui_PrefLineEdit(self.groupBox_2)
        self.StartCell.setObjectName(u"StartCell")
        self.StartCell.setEnabled(False)
        self.StartCell.setGeometry(QRect(10, 100, 117, 26))
        self.StartCell.setFont(font1)
        self.StartCell.setProperty("prefEntry", u"StartCell")
        self.StartCell.setProperty("prefPath", u"TechDrawTitleBlockUtility")
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QRect(135, 105, 276, 16))
        font2 = QFont()
        font2.setBold(False)
        font2.setItalic(True)
        self.label_2.setFont(font2)
        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(5, 0, 421, 131))
        self.groupBox_3.setFont(font)
        self.urlLabel = Gui_UrlLabel(self.groupBox_3)
        self.urlLabel.setObjectName(u"urlLabel")
        self.urlLabel.setGeometry(QRect(10, 15, 401, 26))
        self.urlLabel.setFont(font1)
        self.urlLabel.setTextFormat(Qt.RichText)
        self.urlLabel.setWordWrap(True)
        self.IncludeLengthUnit = Gui_PrefCheckBox(self.groupBox_3)
        self.IncludeLengthUnit.setObjectName(u"IncludeLengthUnit")
        self.IncludeLengthUnit.setGeometry(QRect(10, 45, 121, 17))
        self.IncludeLengthUnit.setFont(font1)
        self.IncludeLengthUnit.setProperty("prefEntry", u"IncludeLength")
        self.IncludeLengthUnit.setProperty("prefPath", u"TechDrawTitleBlockUtility")
        self.IncludeAngleUnit = Gui_PrefCheckBox(self.groupBox_3)
        self.IncludeAngleUnit.setObjectName(u"IncludeAngleUnit")
        self.IncludeAngleUnit.setGeometry(QRect(10, 65, 121, 17))
        self.IncludeAngleUnit.setFont(font1)
        self.IncludeAngleUnit.setProperty("prefEntry", u"IncludeAngle")
        self.IncludeAngleUnit.setProperty("prefPath", u"TechDrawTitleBlockUtility")
        self.IncludeMassUnit = Gui_PrefCheckBox(self.groupBox_3)
        self.IncludeMassUnit.setObjectName(u"IncludeMassUnit")
        self.IncludeMassUnit.setGeometry(QRect(10, 85, 121, 17))
        self.IncludeMassUnit.setFont(font1)
        self.IncludeMassUnit.setProperty("prefEntry", u"IncludeMass")
        self.IncludeMassUnit.setProperty("prefPath", u"TechDrawTitleBlockUtility")
        self.IncludeNoOfSheets = Gui_PrefCheckBox(self.groupBox_3)
        self.IncludeNoOfSheets.setObjectName(u"IncludeNoOfSheets")
        self.IncludeNoOfSheets.setGeometry(QRect(10, 105, 156, 17))
        self.IncludeNoOfSheets.setFont(font1)
        self.IncludeNoOfSheets.setProperty("prefEntry", u"IncludeNoOfSheets")
        self.IncludeNoOfSheets.setProperty("prefPath", u"TechDrawTitleBlockUtility")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(5, 390, 401, 16))
        font3 = QFont()
        font3.setItalic(True)
        self.label.setFont(font3)
#if QT_CONFIG(shortcut)
        self.urlLabel.setBuddy(self.urlLabel)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.IncludeLengthUnit, self.IncludeAngleUnit)
        QWidget.setTabOrder(self.IncludeAngleUnit, self.IncludeMassUnit)
        QWidget.setTabOrder(self.IncludeMassUnit, self.UseExternalSource)
        QWidget.setTabOrder(self.UseExternalSource, self.UseFileName)
        QWidget.setTabOrder(self.UseFileName, self.DrawingNumber)

        self.retranslateUi(Form)
        self.UseExternalSource.toggled.connect(self.ExternalFileChooser.setEnabled)
        self.UseFileName.toggled.connect(self.urlLabel_2.setEnabled)
        self.UseFileName.toggled.connect(self.DrawingNumber.setEnabled)
        self.UseExternalSource.toggled.connect(self.SheetName.setEnabled)
        self.UseExternalSource.toggled.connect(self.label_2.setVisible)
        self.UseExternalSource.toggled.connect(self.StartCell.setEnabled)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        self.groupBox.setTitle(QCoreApplication.translate("Form", u"Drawing number", None))
        self.UseFileName.setText(QCoreApplication.translate("Form", u"Use filename as drawing number", None))
        self.urlLabel_2.setText(QCoreApplication.translate("Form", u"Field for drawing number:", None))
        self.DrawingNumber.setInputMask("")
        self.DrawingNumber.setText("")
        self.DrawingNumber.setPlaceholderText(QCoreApplication.translate("Form", u"Enter the name of  the field.", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Form", u"External source", None))
        self.ExternalFileChooser.setFileName("")
        self.ExternalFileChooser.setFilter(QCoreApplication.translate("Form", u"*.xlsx", None))
        self.UseExternalSource.setText(QCoreApplication.translate("Form", u"Use external source", None))
        self.SheetName.setInputMask("")
        self.SheetName.setText("")
        self.SheetName.setPlaceholderText(QCoreApplication.translate("Form", u"Enter the name of sheet.", None))
        self.StartCell.setInputMask("")
        self.StartCell.setText("")
        self.StartCell.setPlaceholderText(QCoreApplication.translate("Form", u"Enter the start cell", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Cell adress must be like \"B1\". If empty, A1 will be used.", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Form", u"Included items", None))
        self.urlLabel.setText(QCoreApplication.translate("Form", u"The following items can be included even when the titleblock does not have them:", None))
        self.IncludeLengthUnit.setText(QCoreApplication.translate("Form", u"Include lengths", None))
        self.IncludeAngleUnit.setText(QCoreApplication.translate("Form", u"Include angles", None))
        self.IncludeMassUnit.setText(QCoreApplication.translate("Form", u"Include mass", None))
        self.IncludeNoOfSheets.setText(QCoreApplication.translate("Form", u"Include number of pages", None))
        self.label.setText(QCoreApplication.translate("Form", u"FreeCAD needs to be restarted before changes become active.", None))
        pass
    # retranslateUi

